# Generated by Django 3.1.3 on 2023-10-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='dealer_id',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
