# Generated by Django 3.1.3 on 2023-10-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20231024_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carmodel',
            name='car_types',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Wagon', 'Wagon'), ('Minivan', 'Minivan')], default='Sedan', max_length=50),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='carmake',
            name='name',
            field=models.CharField(default='Make', max_length=100),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(default='Car', max_length=100),
        ),
    ]
